---
title: "GK Zone"
author: "Joseph Kroymann"
date: "1/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE}
library(worldfootballR)
library(tidyverse)
library(ggplot2)
library(ggiraph)
library(MetBrewer)
library(grDevices)
```

```{r, echo=FALSE}
gk_data <- fb_big5_advanced_season_stats(season_end_year = 2022,
                                            stat_type = "keepers",
                                            team_or_player = "player")

gk_data_adv <- fb_big5_advanced_season_stats(season_end_year = 2022,
                                            stat_type = "keepers_adv",
                                            team_or_player = "player")

passing_data <- fb_big5_advanced_season_stats(season_end_year = 2022,
                                                 stat_type = "passing",
                                                 team_or_player = "player") %>%
  filter(Comp == "Premier League", Pos == "GK")

pl_keepers <- gk_data %>%
  filter(Comp == "Premier League", Min_Playing > 900)

pl_keepers_adv <- merge(gk_data_adv, pl_keepers)

pl_keepers_passing <- merge(merge(
  gk_data_adv,
  passing_data),
  pl_keepers)
  
colnames(pl_keepers_adv)[colnames(pl_keepers_adv) == "#OPA_Sweeper"] <- "OPA_Sweeper"
colnames(pl_keepers_adv)[colnames(pl_keepers_adv) == "#OPA_per_90_Sweeper"] <- "OPA_Sweeper_per_90"
colnames(pl_keepers_adv)[colnames(pl_keepers_adv) == "_per_90_Expected"] <- "per_90"
colnames(pl_keepers_adv)[colnames(pl_keepers_adv) == "PSxG+_per__minus__Expected"] <- "PSxG_minus_GA"
```

```{r, echo=FALSE}
# how to accumulate expected goals scored against each goalie?? ( not possible w/fbref :( )
```

```{r, echo=FALSE}
prettyZero <- function(l){
    max.decimals = max(nchar(str_extract(l, "\\.[0-9]+")), na.rm = T)-1
    lnew = formatC(l, replace.zero = T, zero.print = "0",
        digits = max.decimals, format = "f", preserve.width=T)
    return(lnew)
}

# who's beating the model?
gk_model <- function(data) {
  ggplot(data = data, aes(x = SoTA, y = PSxG_minus_GA, colour = Save_percent)) +
           xlim(40, 100) +
           geom_vline(xintercept = 70, colour = "white", linetype = "dashed") +
           geom_hline(yintercept = 0, colour = "white", linetype = "dashed") +
           geom_point_interactive(aes(size = 3, tooltip = paste(Player, " - ", Squad, "\n",
                                                                "PSxG - GA: ", PSxG_minus_GA, "\n",
                                                                "SoTA: ", SoTA, "\n",
                                                                "GA: ", GA,
                                                                sep = ),
                                      data_id = Playerf)) + 
           scale_colour_gradientn(colours = met.brewer("OKeeffe2", n = 5)) +
           scale_y_continuous(limits = c(-8, 8),
                              breaks = c(-8, -6, -4, -2, 0, 2, 4, 6, 8)) +
           labs(title = "Who's Beating the Model? (And Does it Matter?)",
                subtitle = "Shot Stopping Ability by Shots on Target for PL GK's (> 900 minutes played)") +
           xlab("Shots on Target Against") +
           ylab("Post-Shot Expected Goals - Goals Allowed per 90") +
           guides(size = FALSE,
                  colour = guide_colourbar(label.position = "bottom",
                                           title.position = "top",
                                           title = "Save %",
                                           )
                  ) +
           theme(
             text = element_text(colour = "white"),
             title = element_text(size = 12),
            
             plot.background = element_rect(fill = "black"),
            
             axis.title = element_text(colour = "white", size = 10),
             axis.title.y = element_text(margin = margin(0, 7.5, 0, 5)),
             axis.title.x = element_text(margin = margin(2.5, 0, 5, 0)),
             axis.text = element_text(colour = "white"),
             axis.ticks = element_line(colour = "white", linetype = "longdash"),
             axis.line = element_line(colour = "white"),
             
             panel.background = element_rect(colour = "black", fill = "black"),
             panel.grid = element_blank(),
            
             legend.position = c(0.175, 0.8),
             legend.direction = "horizontal",
             legend.background = element_rect(colour = "white", fill = "black", linetype = "dashed"),
             legend.text = element_text(colour = "white"),
             legend.title = element_text(colour = "white"),
             legend.title.align = 0.5,
             legend.key.size = unit(0.75, "cm")
)}

girafe(ggobj = gk_model,
       width_svg = 8, height_svg = 5)
```

```{r, echo=FALSE}
gk_sweeper <- function(data) {
  ggplot(data = data, aes(x = AvgDist_Sweeper, y = OPA_Sweeper_per_90)) +
    geom_text(aes(x = 18, y = 0.25, label = "Outside of Box", hjust = 1.25), colour = "white") +
    geom_text(aes(x = 12, y = 1.41, label = "Penalty Spot", hjust = -.25), colour = "white") +
    geom_vline(xintercept = 12, colour = "white", linetype = "dashed") +
    geom_vline(xintercept = 18, colour = "white", linetype = "dashed") +
    
    geom_point_interactive(size = 3, colour = met.brewer("Lakota", n = 1), 
                         aes(tooltip = paste(Player, " - ", Squad, "\n",
                                             "Avg Distance: ", AvgDist_Sweeper, "\n",
                                             "Def Actions per 90: ", OPA_Sweeper_per_90, "\n",
                                             sep = ""),
                             data_id = Player)) +
    labs(title = "Sweeper or Nah?",
        subtitle = "Distance of Defensive Actions from Goal by Activity Outside of the Penalty Area") +
  
  ylab("Defensive Actions Outside of Penalty Area per 90") +
  xlab("Average Distance from Goal of All Defensive Actions (Yards)") +
  
  theme(
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "black"),
    text = element_text(colour = "white"),
    
    plot.background = element_rect(fill = "black"),
    
    axis.line = element_line(colour = "white"),
    axis.text = element_text(colour = "white"),
    axis.title = element_text(colour = "white", size = 10),
    axis.ticks = element_line(colour = "white"),
    axis.title.y = element_text(margin = margin(0, 7.5, 0, 5)),
    axis.title.x = element_text(margin = margin(4, 0, 5, 0)),
    
    title = element_text(size = 14, margin = margin(5, 0, 0, 0))
    )
}

gk_sweeper(pl_keepers_adv)

```

```{r, echo=FALSE}
gk_cross_plot <- function(data) {
  fill_gradient <- colorRampPalette(c("#6ca3a0", "#002a3a"))
  
  ggplot(data = data, aes(x = reorder(Player, +Stp_percent_Crosses), y = Stp_percent_Crosses, fill = CK_Goals,)) +
    geom_bar_interactive(stat = "identity", width = .8, 
                         aes(tooltip = paste0(Player, " - ", Squad, "\n",
                                              "# of Attempted Crosses: ", Opp_Crosses, "\n",
                                              "# of Stopped Crosses: ", Stp_Crosses, "\n",
                                              "% of Crosses Stopped: ", Stp_percent_Crosses, "\n",
                                              "Goals from Corners: ", CK_Goals, 
                                              sep = ""),
                             data_id = Player)) +
    coord_flip() +
    scale_y_continuous(expand = c(0,0), limits = c(0, 15.5), breaks = c(5, 10, 15)) +
    scale_fill_gradientn(colours = fill_gradient(10)) +
    
    ylab("Percentage of Penalty Area Crosses Successfully Stopped") +
    guides(fill = guide_colorbar(label.position = "bottom",
                                 title.position = "top",
                                 title = "Goals from Corners")) +
    
    labs(title = "Controlling the Box - Cross Stopping Ability of Premier League GK's (> 900 Minutes Played)") +
    
    theme(
      title = element_text(colour = "white", hjust = 1),
      
      axis.title.y = element_blank(),
      axis.title.x = element_text(colour = "white"),
      axis.text = element_text(colour = "white"),
      axis.line = element_line(colour = "white"),
      axis.ticks = element_line(colour = "white"),
      
      panel.grid = element_blank(),
      panel.background = element_rect(fill = "black"),
      
      plot.background = element_rect(fill = "black"),
      
      legend.direction = "horizontal",
      legend.background = element_rect(fill = "black", colour = "white", linetype = "dashed"),
      legend.title.align = 0.5,
      legend.text = element_text(colour = "white"),
      legend.title = element_text(colour = "white"),
      legend.key.width = unit(20, "pt"),
      legend.position = c(0.8, 0.25)
    )
}

```


```{r, echo=FALSE}
gkDataCombined %>%
  filter(Min_Playing > 900) %>%
  
  ggplot() +
  
  geom_vline(aes(xintercept = mean(AvgLen_Passes)), colour = "white", linetype = "dashed") +
  geom_hline(aes(yintercept = mean(Cmp_percent_Medium - Cmp_percent_Long)), colour = "white", linetype = "dashed") +
  geom_point(aes(x = AvgLen_Passes, y = Cmp_percent_Medium - Cmp_percent_Long, colour = Comp), size = 3) +
  
  scale_colour_manual(breaks = c("Bundesliga", "La Liga", "Ligue 1", "Premier League", "Serie A"),
                      values = c(met.brewer("Isfahan2")[1], met.brewer("Isfahan2")[2], met.brewer("Isfahan2")[3],
                                 met.brewer("Isfahan2")[4], met.brewer("Isfahan2")[5])) +
  
  guides(colour = guide_legend(
             title = "Competition",
             title.theme = element_text(size = 10, colour = 
                                          "white", hjust = 0.5,
                                        face = "bold"),
             override.aes = list(size = 5)
           )
         ) +
  
  labs(title = "Distribution Drop-off At A Distance",
       subtitle = "Pass Completion Percentage Drop-off by Average Length of Passes",
       x = "Average Length of All Passes (yards)", y = "Medium Pass Completion % - Long Pass Completion %",
       tag = "Data: StatsBomb via fbref.com (GK's with > 900 minutes played in 21/22 season) - Medium = 15-30 yards, Long = 30+ yards") +
   
  theme(
    text = element_text(family = "Roboto", colour = "white"),
    
    panel.grid = element_blank(),
    panel.background = element_rect(fill = "black"),
    
    plot.background = element_rect(fill = "black", colour = "black"),
    plot.title = element_text(margin = margin(6.25,0,3.75,0), face = "bold", size = 18),
    plot.subtitle = element_text(margin = margin(0,0,10,0), face = "plain", size = 14),
    plot.tag = element_text(face = "plain", size = 10),
    plot.tag.position = c(0.475, 0.00875),
    
    legend.background = element_rect(colour = "white", fill = "black"),
    legend.key = element_rect(fill = "black"),
    legend.title.align = 0.5,
          
    axis.line = element_line(colour = "white"),
    axis.text = element_text(colour = "white"),
    axis.title = element_text(colour = "white", size = 12, face = "bold"),
    axis.ticks = element_line(colour = "white"),
    axis.title.y = element_text(margin = margin(0, 16.25, 0, 15), face = "bold"),
    axis.title.x = element_text(margin = margin(15, 0, 25, 0), face = "bold"),
    
    # legend.position = "none"
  )
```
